[tool.poetry]
name = "workshop-dados-4"
version = "0.1.0"
description = ""
authors = ["Rafael Joia <rafael.joia@fgv.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
loguru = "^0.7.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
